### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by belkahorry** [rvalieris/conda-tree#15]
Thanks for your amazing work
Recently i got this error in the default env(base) which has never happened before
I reinstalled serveral time and the networkx version is 2.5
Should i add 'sys.setrecursionlimit(100000)' to a certain file?
or how can i fix it?

$ conda-tree deptree --full
Traceback (most recent call last):
  File "/home/UserName/anaconda3/bin/conda-tree", line 10, in <module>
    sys.exit(main())
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/conda_tree.py", line 321, in main
    tree, state = print_dep_tree(g, pk, None, state)
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/conda_tree.py", line 134, in print_dep_tree
    tree_str, state = print_dep_tree(g, pack, pkg, state)
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/conda_tree.py", line 134, in print_dep_tree
    tree_str, state = print_dep_tree(g, pack, pkg, state)
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/conda_tree.py", line 134, in print_dep_tree
    tree_str, state = print_dep_tree(g, pack, pkg, state)
  [Previous line repeated 988 more times]
  File "/home/UserNameanaconda3/lib/python3.8/site-packages/conda_tree.py", line 66, in print_dep_tree
    edges = g.out_edges(pkg) if down_search else g.in_edges(pkg)
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/networkx/classes/digraph.py", line 897, in edges
    return OutEdgeView(self)
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 994, in __init__
    self._adjdict = G._succ if hasattr(G, "succ") else G._adj
  File "/home/UserName/anaconda3/lib/python3.8/site-packages/networkx/classes/digraph.py", line 359, in succ
    return AdjacencyView(self._succ)
RecursionError: maximum recursion depth exceeded

**Comment by belkahorry** [comment]
No, 'conda-tree deptree' works fine

$ conda tree cycles
beautifulsoup4 -> soupsieve -> beautifulsoup4
