### ISSUE TITLE
Error when redirecting output on Windows

### ISSUE THREAD

**Issue by DManowitz** [rvalieris/conda-tree#16]
When I try to redirect the output of "conda-tree deptree" to a file or pipe through more or tee on Windows 10, I get the following error:

Traceback (most recent call last):
  File "C:\Users\manow\anaconda3\Scripts\conda-tree-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\manow\anaconda3\lib\site-packages\conda_tree.py", line 345, in main
    print(''.join(complete_tree), end='')
  File "C:\Users\manow\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-22: character maps to <undefined>

However, if I just let the output go to the console, I have no problem.

**Comment by DManowitz** [comment]
FYI, I tested this both from CMD and from bash (installed from posix conda meta-package), and I get the same error in either.

**Comment by rvalieris** [comment]
hello,

I don't use windows, so I'm not sure what this means, does this also happens with other python scripts ? 
does setting `set PYTHONIOENCODING=utf-8` helps ?

**Comment by DManowitz** [comment]
Setting PYTHONIOENCODING=utf-8 got rid of the crash, but the resulting
output file has many escape codes in it.  I see you have coloarama as a
dependency, so I'm guessing you're trying to color the output.  However,
interestingly, I don't see any colors when I output the results to the
console.

**Comment by rvalieris** [comment]
currently colorama is only being used to dim the package versions, like a dark gray-ish color, I don't know if cmd supports this.

there are 2 issues here I think:

1. there is a `colorama.init()` that detects windows and change the escape codes, the script is not calling this currently, so the escape codes are probably wrong.
2. the deptree output uses [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character), without knowing the encoding, these characters might show up as gibberish in the file

try this:
- add `import colorama; colorama.init()` to the top of the script
- try setting `PYTHONIOENCODING=utf-8` or `PYTHONIOENCODING=utf-16` and check the file results

**Comment by DManowitz** [comment]
Sorry for the delayed reply; it looks like I missed this message when you
originally sent it.  Regardless, it appears that adding the  colorama.init()
call and setting PYTHONIOENCODING=utf-8 has fixed both issues.

--David

**Comment by prusswan** [comment]
More details can be found at tartley/colorama#319

cp1252.py is not showing the exact characters, but once I added `import logging` to that file, the error is thrown in mbcs.py instead:

    UnicodeEncodeError: 'mbcs' codec can't encode character '\u251c' in position 14: invalid character
